# Generated by Django 4.1.2 on 2023-06-11 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_alter_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='chat_image',
            field=models.ImageField(blank=True, upload_to='photos/categories'),
        ),
    ]
